# Generated by Django 4.1.5 on 2023-01-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=20)),
                ('u_type', models.CharField(choices=[('1', 'bidder'), ('2', 'seller')], default='1', max_length=20)),
            ],
        ),
    ]
