# Generated by Django 4.1.5 on 2023-01-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_user_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Profile',
        ),
    ]
