# Generated by Django 4.1.5 on 2023-01-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_delete_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/default.png', upload_to='profile_images'),
        ),
    ]
