# Generated by Django 4.1.5 on 2023-02-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/media/product_image/2616533-200.png', upload_to='media/product_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='sdate',
            field=models.DateField(auto_now=True),
        ),
    ]
